const S={p:'grocery_products_v3',o:'grocery_orders_v3',c:'grocery_customer_info_v3',cloud:'grocery_cloud_config_v1'};
const STATUS=['待处理','配货中','已完成','已取消'];
let products=[],orders=[],customerCart=[],ownerCart=[],role='customer',cat='全部',filter='all',lastOrder='',cloud=null,cloudAt='',syncing=false,timer=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const money=n=>'¥'+round(n).toFixed(2),round=n=>Math.round((Number(n)||0)*100)/100,sum=a=>a.reduce((x,y)=>x+(Number(y)||0),0),id=p=>p+'_'+Date.now()+'_'+Math.random().toString(16).slice(2,8),pad=n=>String(n).padStart(2,'0');
const day=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`,dt=v=>{const d=new Date(v);return `${day(d)} ${pad(d.getHours())}:${pad(d.getMinutes())}`};
const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
function rq(v,p=0){const f=10**p;return Math.round((Number(v)||0)*f)/f}function fq(v,x={}){const p=Number(x.qtyPrecision||0),n=rq(v,p);return p?n.toFixed(p).replace(/\.?0+$/,''):String(Math.round(n))}function step(p){return p.saleMode==='decimal'?0.5:1}
function read(k){try{return JSON.parse(localStorage.getItem(k))}catch{return null}}function write(k,v){localStorage.setItem(k,JSON.stringify(v))}
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),1800)}
function demo(){const n=Date.now();return [['矿泉水','690001','饮料','瓶',.8,2,48,'常温陈列','integer',0],['可乐','690002','饮料','瓶',2.2,3.5,36,'500ml','integer',0],['方便面','690003','食品','包',2.1,4,30,'桶装','integer',0],['纸巾','690004','日用','包',3.5,6,20,'抽纸','integer',0],['苹果','690007','水果','斤',3.2,5.8,20.5,'称重','decimal',2],['鸡蛋','690008','生鲜','斤',4.5,6.5,30.25,'称重','decimal',2]].map((a,i)=>({id:`p_${n}_${i}`,name:a[0],code:a[1],category:a[2],unit:a[3],cost:a[4],price:a[5],stock:a[6],note:a[7],saleMode:a[8],qtyPrecision:a[9],enabled:true,createdAt:new Date(n).toISOString()}))}
function normP(a){return (a||[]).map(p=>{const m=p.saleMode||(['斤','公斤','千克','克','kg','g'].includes(String(p.unit).toLowerCase())?'decimal':'integer'),q=Number.isInteger(Number(p.qtyPrecision))?Number(p.qtyPrecision):(m==='decimal'?2:0);return {...p,saleMode:m,qtyPrecision:q,stock:rq(p.stock,q)}})}
function normO(a){return (a||[]).map(o=>({...o,channel:o.channel||'owner',customer:o.customer||null,status:STATUS.includes(o.status)?o.status:'待处理',stockDeducted:!!o.stockDeducted}))}
function cloudFromUrl(){const u=new URLSearchParams(location.search),url=u.get('cloudUrl'),anonKey=u.get('cloudKey'),storeId=u.get('storeId');return url&&anonKey&&storeId?{url:url.replace(/\/$/,''),anonKey,storeId}:null}
async function init(){cloud=cloudFromUrl()||read(S.cloud);if(cloud)write(S.cloud,cloud);products=normP(read(S.p)||demo());orders=normO(read(S.o)||[]);if(cloudOk())await pull(true);bind();fillCustomer();fillCloud();startSync();switchRole(new URLSearchParams(location.search).get('role')==='owner'?'owner':'customer');render()}
function bind(){ $$('.role-tabs button').forEach(b=>b.onclick=()=>switchRole(b.dataset.role)); $$('[data-page]').forEach(b=>b.onclick=()=>show(b.dataset.page)); $('#resetBtn').onclick=reset; $('#customerSearch').oninput=renderCustomerShop; $('#customerForm').onsubmit=submitCustomer; $('#newProductBtn').onclick=()=>openProduct(); $('#cancelProductBtn').onclick=closeProduct; $('#productForm').onsubmit=saveProduct; $('#productSearch').oninput=renderProducts; $('#importPurchaseBtn').onclick=importPurchase; $('#ownerProductSearch').oninput=renderOwnerSale; $('#clearOwnerCartBtn').onclick=()=>{ownerCart=[];renderOwnerCart()}; $('#saveOwnerOrderBtn').onclick=saveOwnerOrder; $('#importOrderTextBtn').onclick=importOrderText; $('#statusFilter').onclick=e=>{const b=e.target.closest('button');if(!b)return;filter=b.dataset.status;$$('#statusFilter button').forEach(x=>x.classList.toggle('active',x===b));renderOrders()}; $('#saveCloudBtn').onclick=saveCloud; $('#syncBtn').onclick=async()=>{await pull(false);await push();render();toast('同步完成')}; $('#copyClientBtn').onclick=()=>copyLink('customer'); $('#copyOwnerBtn').onclick=()=>copyLink('owner'); $('#exportBtn').onclick=backup; $('#importBtn').onclick=()=>$('#backupInput').click(); $('#backupInput').onchange=restore }
function switchRole(r){role=r;$$('.role-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.role===r));$('#customerNav').classList.toggle('hidden',r!=='customer');$('#ownerNav').classList.toggle('hidden',r!=='owner');$('#roleText').textContent=r==='customer'?'客户下单端':'商家接单端';$('#titleText').textContent=r==='customer'?'街角小店':'小店管家';show(r==='customer'?'customerShop':'ownerHome')}
function show(id){$$('.page').forEach(p=>p.classList.toggle('active',p.id===id));$$('.bottom button').forEach(b=>b.classList.toggle('active',b.dataset.page===id));render();scrollTo({top:0,behavior:'smooth'})}
function render(){renderCustomerShop();renderCustomerCart();renderConfirm();renderHome();renderProducts();renderOwnerSale();renderOwnerCart();renderOrders();renderStats();renderLinks()}
function renderCustomerShop(){const k=$('#customerSearch').value?.trim().toLowerCase()||'',cs=['全部',...new Set(products.filter(p=>p.enabled).map(p=>p.category||'未分类'))];if(!cs.includes(cat))cat='全部';$('#categoryTabs').innerHTML=cs.map(c=>`<button class="${c===cat?'active':''}" onclick="cat='${encodeURIComponent(c)}';cat=decodeURIComponent(cat);renderCustomerShop()">${esc(c)}</button>`).join('');const arr=products.filter(p=>p.enabled&&(cat==='全部'||p.category===cat)&&match(p,k));$('#customerProducts').innerHTML=arr.length?arr.map(p=>`<article><div><b>${esc(p.name)}</b><div class="meta">${esc(p.category)} ｜ ${p.stock>5?'有货':p.stock>0?'仅剩 '+fq(p.stock,p)+p.unit:'缺货'}</div><div class="price">${money(p.price)} / ${esc(p.unit)}</div></div><button class="primary" ${p.stock<=0?'disabled':''} onclick="addCart(customerCart,'${p.id}',renderCustomerCart)">加入</button></article>`).join(''):'<div class="card meta">没有可售商品</div>'}
function match(p,k){return !k||[p.name,p.code,p.category,p.unit,p.note].filter(Boolean).some(v=>String(v).toLowerCase().includes(k))}
function addCart(cart,pid,done){const p=products.find(x=>x.id===pid);if(!p||!p.enabled)return toast('商品不可售');const it=cart.find(x=>x.productId===pid),s=step(p),q=rq(it?it.qty+s:s,p.qtyPrecision);if(q>p.stock)return toast('库存不足');if(it)it.qty=q;else cart.push({productId:pid,qty:s});done();renderCustomerShop();toast('已加入')}
function renderCart(cart,sel,total,chg,rm,empty){const el=$(sel);if(!cart.length){el.className='cart empty';el.textContent=empty;$(total).textContent=money(0);return}el.className='cart';el.innerHTML=cart.map(i=>{const p=products.find(x=>x.id===i.productId);return p?`<div class="cart-item"><div class="row"><b>${esc(p.name)}</b><span class="price">${money(p.price*i.qty)}</span></div><div class="meta">${money(p.price)} / ${p.unit} ｜ 库存 ${fq(p.stock,p)}${p.unit}</div><div class="qty"><button onclick="${chg}('${i.productId}',${rq(i.qty-step(p),p.qtyPrecision)})">-</button><input value="${fq(i.qty,p)}" onchange="${chg}('${i.productId}',this.value)"><button onclick="${chg}('${i.productId}',${rq(i.qty+step(p),p.qtyPrecision)})">+</button><button onclick="${rm}('${i.productId}')">移除</button></div></div>`:''}).join('');$(total).textContent=money(totalCart(cart))}
function changeCart(cart,pid,v,done){const p=products.find(x=>x.id===pid),q=parseQty(v,p);if(!p||q==null)return done();if(q<=0){removeCart(cart,pid);return done()}if(q>p.stock)return toast('库存不足');const it=cart.find(x=>x.productId===pid);if(it)it.qty=q;done()}
function parseQty(v,p){const n=Number(v);if(!Number.isFinite(n))return toast('数量必须是数字'),null;if((p.qtyPrecision||0)===0&&!Number.isInteger(n))return toast('按件商品数量必须是整数'),null;return rq(n,p.qtyPrecision)}function removeCart(c,pid){const i=c.findIndex(x=>x.productId===pid);if(i>=0)c.splice(i,1)}
function renderCustomerCart(){renderCart(customerCart,'#customerCart','#customerTotal','changeCustomerQty','removeCustomerItem','购物车还是空的');$('#cartBadge').textContent=fq(sum(customerCart.map(i=>i.qty)),{qtyPrecision:2})}window.changeCustomerQty=(id,v)=>changeCart(customerCart,id,v,renderCustomerCart);window.removeCustomerItem=id=>{removeCart(customerCart,id);renderCustomerCart()};
function totalCart(c){return round(sum(c.map(i=>{const p=products.find(x=>x.id===i.productId);return p?p.price*i.qty:0})))}
function itemsFromCart(c){const items=[];for(const i of c){const p=products.find(x=>x.id===i.productId);if(!p||!p.enabled)return toast('存在不可售商品'),null;if(i.qty>p.stock)return toast(`${p.name} 库存不足`),null;items.push({productId:p.id,name:p.name,unit:p.unit,saleMode:p.saleMode,qtyPrecision:p.qtyPrecision,qty:i.qty,price:p.price,cost:p.cost,subtotal:round(p.price*i.qty)})}return items}
function submitCustomer(e){e.preventDefault();if(!customerCart.length)return toast('请先选择商品');const name=$('#customerName').value.trim(),phone=$('#customerPhone').value.trim(),address=$('#customerAddress').value.trim(),note=$('#customerNote').value.trim();if(!name||!phone||!address)return toast('请填写收货信息');if($('#saveCustomerInfo').checked)write(S.c,{name,phone,address});const items=itemsFromCart(customerCart);if(!items)return;const o={id:id('o'),orderNo:orderNo(),createdAt:new Date().toISOString(),channel:'customer',customer:{name,phone,address},items,total:round(sum(items.map(x=>x.subtotal))),status:'待处理',note,stockDeducted:false};orders.unshift(o);lastOrder=o.id;customerCart=[];$('#customerForm').reset();saveOrders();show('customerDone');toast('订单已提交')}
function fillCustomer(){const c=read(S.c);if(!c)return;$('#customerName').value=c.name||'';$('#customerPhone').value=c.phone||'';$('#customerAddress').value=c.address||''}
function renderConfirm(){const o=orders.find(x=>x.id===lastOrder)||orders.find(x=>x.channel==='customer');$('#confirmBox').innerHTML=o?`<div class="card"><span class="badge">已提交</span><h2>订单等待店主处理</h2><p class="meta">订单编号：${o.orderNo}<br>${dt(o.createdAt)}</p>${o.items.map(i=>`<div class="row"><span>${esc(i.name)} x ${fq(i.qty,i)}${i.unit}</span><b>${money(i.subtotal)}</b></div>`).join('')}<div class="total"><span>总金额</span><b>${money(o.total)}</b></div><div class="notice">订单已提交，请等待店主确认。</div></div>`:'<div class="card meta">还没有提交订单</div>'}
function renderHome(){const pend=orders.filter(o=>o.status==='待处理').length,today=orders.filter(o=>o.status==='已完成'&&day(new Date(o.createdAt))===day(new Date()));$('#pendingCount').textContent=pend;$('#todayCount').textContent=today.length;$('#todaySales').textContent=money(sum(today.map(o=>o.total)));$('#productCount').textContent=products.length}
function openProduct(pid=''){const p=products.find(x=>x.id===pid);$('#productForm').classList.remove('hidden');$('#productId').value=p?.id||'';$('#productName').value=p?.name||'';$('#productCode').value=p?.code||'';$('#productCategory').value=p?.category||'';$('#productUnit').value=p?.unit||'';$('#productMode').value=p?.saleMode||'integer';$('#productPrecision').value=p?.qtyPrecision??0;$('#productCost').value=p?.cost??'';$('#productPrice').value=p?.price??'';$('#productStock').value=p?.stock??'';$('#productNote').value=p?.note||'';$('#productEnabled').checked=p?p.enabled:true}function closeProduct(){$('#productForm').reset();$('#productForm').classList.add('hidden')}
function saveProduct(e){e.preventDefault();const m=$('#productMode').value,q=m==='decimal'?Number($('#productPrecision').value):0,p={name:$('#productName').value.trim(),code:$('#productCode').value.trim(),category:$('#productCategory').value.trim()||'未分类',unit:$('#productUnit').value.trim()||'件',saleMode:m,qtyPrecision:q,cost:round($('#productCost').value),price:round($('#productPrice').value),stock:rq($('#productStock').value,q),note:$('#productNote').value.trim(),enabled:$('#productEnabled').checked};if(!p.name)return toast('请输入商品名称');const pid=$('#productId').value;if(pid)products=products.map(x=>x.id===pid?{...x,...p,updatedAt:new Date().toISOString()}:x);else products.unshift({id:id('p'),...p,createdAt:new Date().toISOString()});saveProducts();closeProduct();render();toast('商品已保存')}
function renderProducts(){const k=$('#productSearch').value?.toLowerCase()||'',arr=products.filter(p=>match(p,k));$('#productList').innerHTML=arr.length?arr.map(p=>`<article><div class="row"><b>${esc(p.name)}</b><b class="price">${money(p.price)}</b></div><div class="meta">${p.category} ｜ ${p.saleMode==='decimal'?'称重':'按件'} ｜ 库存 ${fq(p.stock,p)}${p.unit} ｜ 成本 ${money(p.cost)}</div><div class="grid"><button onclick="openProduct('${p.id}')">编辑</button><button onclick="toggleProduct('${p.id}')">${p.enabled?'停用':'启用'}</button><button class="danger" onclick="deleteProduct('${p.id}')">删除</button></div></article>`).join(''):'<div class="card meta">暂无商品</div>'}
window.openProduct=openProduct;window.toggleProduct=id=>{products=products.map(p=>p.id===id?{...p,enabled:!p.enabled}:p);saveProducts();render()};window.deleteProduct=id=>{if(!confirm('确认删除商品？'))return;products=products.filter(p=>p.id!==id);saveProducts();render()};
function importPurchase(){const lines=$('#purchaseText').value.trim().split(/\n+/),add=[];for(const line of lines){const a=line.split(/[,，\t]/).map(x=>x.trim());if(a.length<7)continue;const mode=/称重|重量|斤|公斤|kg|g/i.test((a[7]||'')+a[3])?'decimal':'integer',q=mode==='decimal'?2:0;add.push({id:id('p'),name:a[0],code:a[1],category:a[2]||'未分类',unit:a[3]||'件',cost:round(a[4]),price:round(a[5]),stock:rq(a[6],q),saleMode:mode,qtyPrecision:q,note:'进货单导入',enabled:true,createdAt:new Date().toISOString()})}for(const p of add){const i=products.findIndex(x=>p.code&&x.code===p.code);if(i>=0)products[i]={...products[i],...p,id:products[i].id,stock:rq((Number(products[i].stock)||0)+p.stock,p.qtyPrecision)};else products.unshift(p)}saveProducts();$('#purchaseText').value='';render();toast(`已导入 ${add.length} 个商品`)}
function renderOwnerSale(){const k=$('#ownerProductSearch').value?.toLowerCase()||'',arr=products.filter(p=>p.enabled&&match(p,k));$('#ownerProductsForSale').innerHTML=arr.map(p=>`<button ${p.stock<=0?'disabled':''} onclick="addCart(ownerCart,'${p.id}',renderOwnerCart)"><b>${esc(p.name)}</b><div class="price">${money(p.price)}</div><div class="meta">库存 ${fq(p.stock,p)}${p.unit}</div></button>`).join('')||'<div class="card meta">没有可售商品</div>'}
function renderOwnerCart(){renderCart(ownerCart,'#ownerCart','#ownerTotal','changeOwnerQty','removeOwnerItem','还没有选择商品')}window.changeOwnerQty=(id,v)=>changeCart(ownerCart,id,v,renderOwnerCart);window.removeOwnerItem=id=>{removeCart(ownerCart,id);renderOwnerCart()};
function importOrderText(){const arr=$('#ocrText').value.trim().split(/\n+/).map(l=>l.match(/^(.+?)[\s,，xX*＊]*(\d+(?:\.\d+)?)/)).filter(Boolean);let n=0;for(const m of arr){const p=products.find(x=>x.enabled&&(m[1].includes(x.name)||x.name.includes(m[1].trim())));if(!p)continue;const q=rq(m[2],p.qtyPrecision);if(q<=p.stock){const it=ownerCart.find(x=>x.productId===p.id);it?it.qty=rq(Math.min(it.qty+q,p.stock),p.qtyPrecision):ownerCart.push({productId:p.id,qty:q});n++}}renderOwnerCart();toast(`已导入 ${n} 项`)}
function saveOwnerOrder(){if(!ownerCart.length)return toast('请先选择商品');const items=itemsFromCart(ownerCart);if(!items)return;const o={id:id('o'),orderNo:orderNo(),createdAt:new Date().toISOString(),channel:'owner',customer:null,items,total:round(sum(items.map(i=>i.subtotal))),status:'已完成',note:$('#ownerNote').value.trim(),stockDeducted:true};if(!deduct(o))return toast('库存不足');orders.unshift(o);ownerCart=[];$('#ownerNote').value='';saveOrders();show('ownerOrders');toast('订单已保存')}
function renderOrders(){const arr=orders.filter(o=>filter==='all'||o.status===filter);$('#orderList').innerHTML=arr.length?arr.map(o=>`<article><div class="row"><div><b>${o.orderNo}</b><div class="meta">${dt(o.createdAt)} ｜ ${o.channel==='customer'?'客户下单':'店主开单'}${o.customer?' ｜ '+esc(o.customer.name)+' '+esc(o.customer.phone):''}</div></div><div><b class="price">${money(o.total)}</b><br><span class="badge">${o.status}</span></div></div>${o.customer?`<div class="notice">地址：${esc(o.customer.address)}</div>`:''}${o.items.map(i=>`<div class="row meta"><span>${esc(i.name)} x ${fq(i.qty,i)}${i.unit}</span><span>${money(i.subtotal)}</span></div>`).join('')}<select onchange="updateStatus('${o.id}',this.value)">${STATUS.map(s=>`<option ${s===o.status?'selected':''}>${s}</option>`).join('')}</select> <button onclick="removeOrder('${o.id}')">删除</button></article>`).join(''):'<div class="card meta">暂无订单</div>'}
window.updateStatus=(oid,st)=>{const o=orders.find(x=>x.id===oid);if(!o||o.status===st)return;if(st==='已取消'||st==='待处理'){if(o.stockDeducted){restoreStock(o);o.stockDeducted=false}}else if(!o.stockDeducted&&(st==='配货中'||st==='已完成')){if(!deduct(o))return toast('库存不足，无法接单');o.stockDeducted=true}o.status=st;o.updatedAt=new Date().toISOString();saveOrders();render();toast('状态已更新')};window.removeOrder=oid=>{const o=orders.find(x=>x.id===oid);if(!o||!confirm('确认删除订单？'))return;if(o.stockDeducted&&confirm('是否恢复库存？'))restoreStock(o);orders=orders.filter(x=>x.id!==oid);saveOrders();render()};
function deduct(o){for(const i of o.items){const p=products.find(x=>x.id===i.productId);if(!p||p.stock+1e-6<i.qty)return false}products=products.map(p=>{const i=o.items.find(x=>x.productId===p.id);return i?{...p,stock:rq(p.stock-i.qty,p.qtyPrecision)}:p});saveProducts();return true}function restoreStock(o){products=products.map(p=>{const i=o.items.find(x=>x.productId===p.id);return i?{...p,stock:rq(p.stock+i.qty,p.qtyPrecision)}:p});saveProducts()}
function renderStats(){const today=orders.filter(o=>o.status==='已完成'&&day(new Date(o.createdAt))===day(new Date())),done=orders.filter(o=>o.status==='已完成'),sales=sum(today.map(o=>o.total)),profit=sum(done.flatMap(o=>o.items.map(i=>(i.price-i.cost)*i.qty)));$('#statSales').textContent=money(sales);$('#statOrders').textContent=today.length;$('#statProfit').textContent=money(profit);const all=sum(done.map(o=>o.total));$('#statRate').textContent=all?((profit/all)*100).toFixed(1)+'%':'0%';const r={};done.forEach(o=>o.items.forEach(i=>{r[i.name]??={qty:0,amount:0};r[i.name].qty+=i.qty;r[i.name].amount+=i.subtotal}));$('#rankList').innerHTML=Object.entries(r).sort((a,b)=>b[1].amount-a[1].amount).map(([n,v],i)=>`<article class="row"><span>${i+1}. ${esc(n)} x ${fq(v.qty,{qtyPrecision:2})}</span><b>${money(v.amount)}</b></article>`).join('')||'<div class="card meta">暂无数据</div>';$('#trendList').innerHTML=[...Array(7)].map((_,i)=>{const d=new Date();d.setDate(d.getDate()-6+i);const v=sum(done.filter(o=>day(new Date(o.createdAt))===day(d)).map(o=>o.total));return `<div class="row"><span>${d.getMonth()+1}/${d.getDate()}</span><b>${money(v)}</b></div>`}).join('')}
function orderNo(){const d=new Date();return `OD${d.getFullYear()}${pad(d.getMonth()+1)}${pad(d.getDate())}${pad(d.getHours())}${pad(d.getMinutes())}${pad(d.getSeconds())}${Math.floor(Math.random()*90+10)}`}
function saveProducts(){write(S.p,products);push()}function saveOrders(){write(S.o,orders);push()}
function reset(){if(!confirm('确认重置示例数据？'))return;products=demo();orders=[];customerCart=[];ownerCart=[];saveProducts();saveOrders();render()}
function backup(){const blob=new Blob([JSON.stringify({products,orders,customerInfo:read(S.c)},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='grocery-backup.json';a.click();URL.revokeObjectURL(a.href)}function restore(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{const d=JSON.parse(r.result);products=normP(d.products);orders=normO(d.orders);saveProducts();saveOrders();render()};r.readAsText(f,'utf-8')}
function cloudOk(){return !!(cloud?.url&&cloud?.anonKey&&cloud?.storeId)}function fillCloud(){$('#cloudUrl').value=cloud?.url||'';$('#cloudKey').value=cloud?.anonKey||'';$('#storeId').value=cloud?.storeId||'store_001';cloudStatus();renderLinks()}function saveCloud(){cloud={url:$('#cloudUrl').value.trim().replace(/\/$/,''),anonKey:$('#cloudKey').value.trim(),storeId:$('#storeId').value.trim()||'store_001'};write(S.cloud,cloud);push().then(()=>{startSync();renderLinks();toast('云配置已保存')})}function headers(){return{apikey:cloud.anonKey,Authorization:`Bearer ${cloud.anonKey}`,'Content-Type':'application/json'}}function api(){return `${cloud.url}/rest/v1/grocery_store_state`}
async function pull(silent){if(!cloudOk()||syncing)return;syncing=true;try{const res=await fetch(`${api()}?store_id=eq.${encodeURIComponent(cloud.storeId)}&select=*`,{headers:headers()});if(!res.ok)throw Error(await res.text());const rows=await res.json();if(!rows.length){await push();return}const r=rows[0];if(r.updated_at===cloudAt)return;products=normP(r.products);orders=normO(r.orders);cloudAt=r.updated_at;write(S.p,products);write(S.o,orders);cloudStatus('云数据已同步 '+dt(new Date()));render();if(!silent)toast('已拉取云端数据')}catch(e){console.warn(e);cloudStatus('云同步失败，请检查配置','err')}finally{syncing=false}}
async function push(){if(!cloudOk())return;const now=new Date().toISOString(),body={store_id:cloud.storeId,products,orders,settings:{},updated_at:now};try{const res=await fetch(`${api()}?on_conflict=store_id`,{method:'POST',headers:{...headers(),Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify(body)});if(!res.ok)throw Error(await res.text());const rows=await res.json();cloudAt=rows[0]?.updated_at||now;cloudStatus('云数据已保存 '+dt(now))}catch(e){console.warn(e);cloudStatus('云保存失败，本地已保存','err')}}function startSync(){if(timer)clearInterval(timer);if(cloudOk())timer=setInterval(()=>pull(true),3000);cloudStatus()}
function cloudStatus(msg,cls){const el=$('#cloudStatus');if(!cloudOk()){el.className='notice warn';el.textContent='未配置云数据库，当前使用本地数据';return}el.className='notice '+(cls||'');el.textContent=msg||`已连接云店铺：${cloud.storeId}`}function roleLink(r){const u=new URL(location.href);u.pathname=u.pathname.replace(/[^/]*$/,r==='owner'?'owner.html':'client.html');u.search='';u.searchParams.set('role',r);if(cloudOk()){u.searchParams.set('cloudUrl',cloud.url);u.searchParams.set('cloudKey',cloud.anonKey);u.searchParams.set('storeId',cloud.storeId)}return u.toString()}function renderLinks(){$('#clientLink').value=cloudOk()?roleLink('customer'):'';$('#ownerLink').value=cloudOk()?roleLink('owner'):''}function copyLink(r){if(!cloudOk())return toast('请先保存云配置');const txt=roleLink(r);navigator.clipboard?navigator.clipboard.writeText(txt).then(()=>toast('链接已复制')):prompt('复制链接',txt)}
init();
